#!/bin/sh
set -e

config_dir="/etc/files-backup"

case "$1" in
    remove|deconfigure)
        # Remove /etc/files-backup directory if it is empty
        if [ -d "$config_dir" ] && [ -z "$(ls -A $config_dir)" ]; then
          rmdir $config_dir
        fi

        # Remove the cronjob from the current user's crontab
        (crontab -l | grep -v "/usr/share/files-backup/files-backup-scheduler" ) | crontab -

        ;;
    *)
        # Do nothing on other actions
        exit 0
        ;;
esac

# Continue with package removal
exit 0
