#!/bin/sh
set -e

config_dir="/etc/files-backup"

if [ "$1" = "remove" ]; then
  # Remove /etc/files-backup directory if it is empty
  if [ -d "$config_dir" ] && [ -z "$(ls -A $config_dir)" ]; then
    rmdir $config_dir
  fi
fi

# Continue with package removal
exit 0
