#!/bin/bash

set -e

case "$1" in
    configure)
        # Add the cronjob to the current user's crontab
        (crontab -l ; echo "0 2 * * * /usr/share/files-backup/files-backup-scheduler") | crontab -
        ;;
    *)
        # Do nothing on other actions
        exit 0
        ;;
esac

exit 0
